#ifndef CONFIGUREFILE_H
#define CONFIGUREFILE_H

//TreeView=1 OR TableView=0
#define DISPLAY_VIEW 0

//TIME_FILTER_IS_STRING is 0 (QTimeEdit) OR 1 (QString)
#define TIME_FILTER_IS_STRING 1

//NOT_HIDE_ROWS_WHEN_FILTER 0 OR 1
#define NOT_HIDE_ROWS_WHEN_FILTER 1

//CONVENIENCE FOR DEBUG
#define AUTO_OPEN_DIR 0

#define ROWS_EMIT 100

#define MARK_GO_NEXT_ROW 1

#define HIDE_VERTICAL_HEAD_DATA 1

#define SHOW_EVENT_WITH_TEXTEDIT 1
#endif // CONFIGUREFILE_H
